keymap = {
    "super_l": "winleft",
    "control_l": "ctrlleft",
    "alt_l": "altleft",
    "super_r": "winright",
    "control_r": "ctrlright",
    "alt_r": "altright",
    "semicolon": ";",
    "apostrophe": "'",
    "slash": "/",
    "period": ".",
    "comma": ",",
    "bracketleft": "[",
    "bracketright": "]",
    "grave": "`",
    "minus": "-",
    "equal": "=",
    "caps_lock": "capslock",
    "page_up": "pgup",
    "page_down": "pgdn",
    "next": "pgdn",
}
